Cv_Maker_App/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'Cv_Maker_App'

urlpatterns = [
    path('cv/<slug:slug>/', views.index, name='cv'),
    path('my_cv_list/', views.MyCv.as_view(), name='my_cv'),
    path('cvpdf/view/<str:id>/', views.ViewPass.as_view(), name='cvpdf'),
    path('create-cv/', views.CreateCv, name='create-cv'),

]

Login_App/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'Login_App'

urlpatterns = [
    path('signup/', views.sign_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')


]

cv_maker_project/urls.py
from Cv_Maker_App import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Cv_Maker_App.views import home
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('', views.home, name='home'),
    path('cv/', include('Cv_Maker_App.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cv_Maker_App/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
import uuid
# Create your models here.


class CvMaker(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='post_user')
    fullname = models.CharField(
        max_length=200, verbose_name='own name', blank=False)
    email = models.EmailField(blank=False)
    phone_number = models.CharField(max_length=12)
    sex = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('SheMale', 'SheMale'),
    )
    birth_date = models.DateField(blank=False)
    zender = models.CharField(max_length=7, choices=sex)
    cv_picture = models.ImageField(
        verbose_name='Upload CV Picture', upload_to='picture', blank=False)
    website = models.URLField(blank=True)
    present_address = models.CharField(max_length=250, blank=False)
    about = models.TextField(blank=False)
    school_start_date = models.DateField(blank=False)
    school_start_end = models.DateField(blank=False)
    subject = (
        ('Science', 'Science'),
        ('Business', 'Business'),
        ('Humanities', 'Humanities')
    )
    ssc_subject = models.CharField(max_length=20, choices=subject, blank=False)
    school_name = models.CharField(max_length=250, blank=False)
    hsc_start_date = models.DateField(blank=False)
    hsc_start_end = models.DateField(blank=False)
    hsc_subject = models.CharField(max_length=20, choices=subject, blank=False)
    college_name = models.CharField(max_length=250, blank=False)

    first_job = models.CharField(max_length=250, blank=True)
    first_job_title = models.CharField(max_length=250, blank=True)
    first_job_date = models.CharField(max_length=10, blank=True, null=True)
    present_job = models.CharField(max_length=250, blank=True)
    present_job_title = models.CharField(max_length=250, blank=True)
    present_job_date = models.DateField(blank=True, null=True)

    skils_title_1 = models.CharField(max_length=20, blank=True)
    skills_percentage_1 = models.IntegerField(blank=True)
    skils_title_2 = models.CharField(max_length=20, blank=True)
    skills_percentage_2 = models.IntegerField(blank=True)
    skils_title_3 = models.CharField(max_length=20, blank=True)
    skills_percentage_3 = models.IntegerField(blank=True)
    skils_title_4 = models.CharField(max_length=20, blank=True)
    skills_percentage_4 = models.IntegerField(blank=True)
    skils_title_5 = models.CharField(max_length=20, blank=True)
    skills_percentage_5 = models.IntegerField(blank=True)
    facebook = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    linkdin = models.URLField(blank=True)
    youtube = models.URLField(blank=True)
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ['-publish_date']

    def save(self):
        self.slug = slugify(self.email + '-' + str(uuid.uuid4()))
        super(CvMaker, self).save()

    def __str__(self):
        return self.fullname

Cv_Maker_App/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields, widgets
from .models import CvMaker


class CvMakerForm(ModelForm):
    fullname = forms.CharField(required=True, label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Your Full Name'}))
    email = forms.EmailField(required=True, label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Your Email'}))
    phone_number = forms.CharField(required=True, label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Your Phone Number'}))
    zender = forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'form-control', 'placeholder': 'Enter Your Zender', })),
    website = forms.URLField(required=True, label='', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter Your Website Portfolio', })),
    present_address = forms.TextInput(),
    birth_date = forms.DateField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date'}),)
    school_start_date = forms.DateField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date'}),)
    school_start_end = forms.DateField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date'}),)
    hsc_start_date = forms.DateField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date'}),)
    hsc_start_end = forms.DateField(required=True, widget=forms.DateInput(
        attrs={'class': 'form-control', 'type': 'date'}),)

    class Meta:
        model = CvMaker
        exclude = ('user', 'slug')
        widgets = {

        }

Cv_Maker_App/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from .models import CvMaker
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator
from django.shortcuts import render, get_object_or_404
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from django.views import View
from xhtml2pdf import pisa
from .forms import CvMakerForm
import uuid
# Create your views here.


def home(request):
    return render(request, 'base.html')


@login_required
def CreateCv(request):
    form = CvMakerForm()
    if request.method == 'POST':
        form = CvMakerForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.save(commit=False)
            data.user = request.user
            data.slug = data.fullname.replace(
                " ", "-") + "-" + str(uuid.uuid4())
            data.save()
            return HttpResponseRedirect(reverse('home'))
    return render(request, 'Cv_Maker_App/create-cv.html', context={'form': form})


@login_required
def index(request, slug):
    cv = CvMaker.objects.get(slug=slug)
    return render(request, 'Cv_Maker_App/cvdesign.html', context={'cv': cv})


class MyCv(LoginRequiredMixin, TemplateView):
    template_name = "Cv_Maker_App/mycvlist.html"


class ViewPass(View):
    @method_decorator(login_required(login_url='login'))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, id):
        cv = get_object_or_404(CvMaker, id=id)
        #cv = CvMaker.objects.get(slug=slug)
        return render(request, 'Cv_Maker_App/cvdesign.html', context={'cv': cv})

templates/Cv_Maker_App/create-cv.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Sign up{% endblock %}
{% block css_block %}
<style>
    .sign-up {
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
        margin-top: 150px;
        border-bottom: 2px silver;
        margin-bottom: 20px;
    }

    input,
    optgroup,
    select,
    textarea {
        margin: 5px;
        padding: 8px;
        width: 95%;
        border-radius: 3px;
        border: 1px solid #e5eaef;
        font-family: inherit;
        font-size: large;
        line-height: inherit;
    }

    .button {
        width: 95%;
        margin-top: 15px;
    }
</style>

{% endblock %}

{% block body_block %}
<center>
    <div class="form-container">
        <div class="sign-up">
            <h4>CV Form</h4><br>

            <form method="POST" enctype="multipart/form-data">
                {{ form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary button">Upload</button>
            </form>
            <hr>
            <br>
        </div>
    </div>
</center>

{% endblock %}

templates/Cv_Maker_App/cvdesign.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>My CV</title>
    <link rel="stylesheet" href="{% static 'css/cvdesign.css' %}">
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <script src="https://raw.githack.com/eKoopmans/html2pdf/master/dist/html2pdf.bundle.js"></script>

    <style>
        .main {
            margin-bottom: 15px;
            border-top: 1px solid;
            border-bottom: 1px solid;
            background: lightblue;
            padding: 0 17px;
        }
    </style>
</head>

<body>

    <div class="resume" id="main">
        <div class="resume_left">
            <div class="resume_profile">
                <img src="/media/{{cv.cv_picture}}" alt="profile_pic">
            </div>
            <div class="resume_content">
                <div class="resume_item resume_info">
                    <div class="title">
                        <p class="bold text-ce">{{cv.fullname}}</p>
                        <p class="regular">Software Engineer</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fas fa-map-signs"></i>
                            </div>
                            <div class="data">
                                {{cv.present_address}}
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-mobile-alt"></i>
                            </div>
                            <div class="data">
                                {{cv.phone_number}}
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fas fa-envelope"></i>
                            </div>
                            <div class="data">
                                {{cv.email}}
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-weebly"></i>
                            </div>
                            <div class="data">
                                {{cv.website}}
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_skills">
                    <div class="title">
                        <p class="bold">skill's</p>
                    </div>
                    <ul>
                        <li>
                            <div class="skill_name">
                                {{cv.skils_title_1}}
                            </div>
                            <div class="skill_progress">
                                <span style="width: {{cv.skills_percentage_1}}%;"></span>
                            </div>
                            <div class="skill_per">{{cv.skills_percentage_1}}%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                {{cv.skils_title_2}}
                            </div>
                            <div class="skill_progress">
                                <span style="width: {{cv.skills_percentage_2}}%;"></span>
                            </div>
                            <div class="skill_per">{{cv.skills_percentage_2}}%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                {{cv.skils_title_3}}
                            </div>
                            <div class="skill_progress">
                                <span style="width: {{cv.skills_percentage_3}}%;"></span>
                            </div>
                            <div class="skill_per">{{cv.skills_percentage_3}}%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                {{cv.skils_title_4}}
                            </div>
                            <div class="skill_progress">
                                <span style="width: {{cv.skills_percentage_4}}%;"></span>
                            </div>
                            <div class="skill_per">{{cv.skills_percentage_4}}%</div>
                        </li>
                        <li>
                            <div class="skill_name">
                                {{cv.skils_title_5}}
                            </div>
                            <div class="skill_progress">
                                <span style="width: {{cv.skills_percentage_5}}%;"></span>
                            </div>
                            <div class="skill_per">{{cv.skills_percentage_5}}%</div>
                        </li>
                    </ul>
                </div>
                <div class="resume_item resume_social">
                    <div class="title">
                        <p class="bold">Social</p>
                    </div>
                    <ul>
                        <li>
                            <div class="icon">
                                <i class="fab fa-facebook-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Facebook</p>
                                <p>{{cv.facebook}}</p>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-twitter-square"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Twitter</p>
                                <p>{{cv.twitter}}</p>
                            </div>
                        </li>
                        <li>
                            <div class="icon">
                                <i class="fab fa-linkedin"></i>
                            </div>
                            <div class="data">
                                <p class="semi-bold">Linkedin</p>
                                <p>{{cv.linkdin}}</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="resume_right">
            <div class="resume_item resume_about">
                <div class="title">
                    <p class="bold">About Me</p>
                </div>
                <p>{{cv.about}}</p>
            </div>
            <div class="resume_item resume_work">
                <div class="title">
                    <p class="bold">Work Experience</p>
                </div>
                <ul>
                    {% if cv.first_job %}
                    <li>
                        <div class="date">{{cv.first_job_date}}</div>
                        <div class="info">
                            <p class="semi-bold">{{cv.first_job_title }}</p>
                            <p>{{ cv.first_job }}</p>
                        </div>
                    </li>
                    {% endif %}
                    {% if cv.present_job %}
                    <li>
                        <div class="date">{{cv.present_job_date}}</div>
                        <div class="info">
                            <p class="semi-bold">{{cv.present_job_title}}</p>
                            <p>{{cv.present_job}}</p>
                        </div>
                    </li>
                    {% endif %}

                </ul>
            </div>
            <div class="resume_item resume_education">
                <div class="title">
                    <p class="bold">Education</p>
                </div>
                <ul>
                    <li>
                        <div class="date">{{cv.school_start_date}} - {{cv.school_start_end}}</div>
                        <div class="info">
                            <p class="semi-bold">{{cv.ssc_subject}}</p>
                            <p>{{ cv.school_name }}</p>
                        </div>
                    </li>
                    <li>
                        <div class="date">{{ cv.hsc_start_date }} - {{cv.hsc_start_end}}</div>
                        <div class="info">
                            <p class="semi-bold">{{ cv.hsc_subject }}</p>
                            <p>{{ cv.college_name }}</p>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="resume_item resume_hobby">
                <div class="title">
                    <p class="bold">Hobby</p>
                </div>
                <ul>
                    <li><i class="fas fa-book"></i></li>
                    <li><i class="fas fa-gamepad"></i></li>
                    <li><i class="fas fa-music"></i></li>
                    <li><i class="fab fa-pagelines"></i></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row ">
            <div class="col-md-12 text-center mb-4">
                <button class="btn btn-warning" id="downloadPdf">
                    Download CV
                </button>
            </div>
        </div>
    </div>

    <script>
        document
            .getElementById("downloadPdf")
            .addEventListener("click", function download() {
                const element = document.getElementById("main");
                html2pdf()
                    .from(element)
                    .save();
            });
    </script>
</body>


</html>

templates/Cv_Maker_App/mycvlist.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %} My Cv{% endblock %}
{% block css_block %}
<style>
    .cv-design {
        margin-top: 150px;
    }
</style>

{% endblock %}

{% block body_block %}

<body>
    <div class="container cv-design">


        {% if user.post_user %}
        {% for mycv in user.post_user.all %}

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th class="text-center" scope="col">User Name</th>
                    <th class="text-center" scope="col">CV Name</th>
                    <th class="text-center" scope="col">Email</th>
                    <th class="text-center" scope="col">View CV</th>
                    <th class="text-center" scope="col">Download CV</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">{{mycv.id}}</th>
                    <td class="text-center">{{mycv.user}}</td>
                    <td class="text-center">{{mycv.fullname}}</td>
                    <td class="text-center">{{mycv.email}}</td>
                    <td class="text-center"> <a href="{% url 'Cv_Maker_App:cv' slug=mycv.slug %}"><i
                                class="fas fa-eye"></i></a>
                    </td>
                    <td class="text-center"><a href="{% url 'Cv_Maker_App:cvpdf' mycv.id %}"><i
                                class="bi bi-download"></i></a></td>

                </tr>

            </tbody>
        </table>

        {% endfor %}
        {% else %}
        <h1>No</h1>
        {% endif %}
    </div>


</body>


{% endblock %}

templates/Cv_Maker_App/prac.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title_block %} Sign up{% endblock %}
{% block css_block %}
<style>
    .sign-up {
        width: 550px;
        border: 1px solid #ccc;
        padding: 40px;
        margin-top: 150px;
        border-bottom: 2px silver;
        margin-bottom: 20px;
    }

    input,
    optgroup,
    select,
    textarea {
        margin: 5px;
        padding: 8px;
        width: 95%;
        border-radius: 3px;
        border: 1px solid #e5eaef;
        font-family: inherit;
        font-size: large;
        line-height: inherit;
    }

    .form {
        margin-left: 25px;
        margin-right: 25px;
    }


    .button {
        width: 95%;
        margin-top: 15px;
    }
</style>

{% endblock %}

{% block body_block %}
<center>
    <div class="form-container">
        <div class="sign-up">
            <h4>CV Form</h4><br>

            <form action="" method="POST" enctype="multipart/form-data" class="form">
                {{ form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary button">Upload</button>
            </form>
            <br>
        </div>
    </div>
</center>

{% endblock %}