Cv_Maker_App/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'Cv_Maker_App'

urlpatterns = [
    path('cv/<slug:slug>/', views.index, name='cv'),
    path('my_cv_list/', views.MyCv.as_view(), name='my_cv'),
    path('cvpdf/view/<str:id>/', views.ViewPass.as_view(), name='cvpdf'),
    path('create-cv/', views.CreateCv, name='create-cv'),

]

Login_App/urls.py
from django.contrib import admin
from django.urls import path
from .import views

app_name = 'Login_App'

urlpatterns = [
    path('signup/', views.sign_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout')


]

cv_maker_project/urls.py
from Cv_Maker_App import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from Cv_Maker_App.views import home
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Login_App.urls')),
    path('', views.home, name='home'),
    path('cv/', include('Cv_Maker_App.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Dosis:300,400,500,,600,700,700i|Lato:300,300i,400,400i,700,700i"
        rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'font/icon.css' %}">
    <link rel="stylesheet" href="{% static 'css/min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
    <title>{% block title_block %} {% endblock %}</title>
    {% block css_block %}

    {% endblock %}
</head>
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <a href="{% url 'home' %}" class="logo mr-auto">

            CV Maker </a>

        <nav class="nav-menu d-none d-lg-block">
            <ul>
                {% if user.is_authenticated %}

                <li><a href="{% url 'Cv_Maker_App:create-cv' %}">Create Your CV </a></li>
                <li><a href="{% url 'Cv_Maker_App:my_cv' %}">Collect CV </a></li>
                <li><a href="#">Edit Profile</a></li>
                <li><a href="{% url 'Login_App:logout' %}"><i class="bi bi-box-arrow-right"></i>Logout</a></li>
                {% else %}

                <li><a href="{% url 'Cv_Maker_App:create-cv' %}"> Create CV </a></li>
                <li><a href="{% url 'Login_App:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'Login_App:login' %}"> Log In</a></li>
                {% endif %}
            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header>

<body>

    {% block body_block %}


    {% endblock %}

    <footer class="text-muted footer">
        <div class="container">
            <p class="text-center">&copy; Made by Nahid Hasan & Nirob</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% block script %} {% endblock %}
</body>

</html>

templates/home.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Dosis:300,400,500,,600,700,700i|Lato:300,300i,400,400i,700,700i"
        rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'font/icon.css' %}">
    <link rel="stylesheet" href="{% static 'css/min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.2/html2pdf.bundle.js"></script>
    <title>{% block title_block %} {% endblock %}</title>
    {% block css_block %}

    {% endblock %}
</head>
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

        <a href="#" class="logo mr-auto">

            CV Maker </a>

        <nav class="nav-menu d-none d-lg-block">
            <ul>

                <li><a href="#"> Apply CV </a></li>
                <li><a href="#">Collect CV </a></li>
                <li><a href="#">Edit Profile</a></li>
                <li><a href="#"><i class="bi bi-box-arrow-right"></i>Logout</a></li>

                <li><a href="#"> Apply </a></li>
                <li><a href="#">Sign Up</a></li>
                <li><a href="#"> Log In</a></li>






            </ul>
        </nav><!-- .nav-menu -->

    </div>
</header>

<body>

    {% block body_block %}


    {% endblock %}

    <footer class="text-muted footer">
        <div class="container">
            <p class="text-center">&copy; Made by Nahid Hasan & Nirob</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    {% block script %} {% endblock %}
</body>

</html>